//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseData
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class Hangar
    {
        [DataMember]
        public string Id { get; set; }
        [DataMember]
        public int MaxContainers { get; set; }
        [DataMember]
        public int PlacedContainers { get; set; }
        [DataMember]
        public string AreaId { get; set; }

        [DataMember]
        public  Area Area { get; set; }
    }
}
