//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class hangar
    {
        [DataMember]
        public string IdHangar { get; set; }
        [DataMember]
        public int MaxContainers { get; set; }
        [DataMember]
        public int FreePlaces { get; set; }
        [DataMember]
        public string Area_IdArea { get; set; }
    
        public virtual area area { get; set; }
    }
}
